version: '3.4'

services:

  ####################################
  #  LOGIC MODULE ON DC 1            #
  ####################################

  logicmodule1:
    image: "bscdataclay/logicmodule:${DATACLAY_CONTAINER_VERSION}"
    ports:
      - "1034:1034"
    env_file:
      - ./env/LM.environment
    environment:
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
    volumes:
      - ./prop/global.properties:/usr/src/dataclay/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/usr/src/dataclay/log4j2.xml:ro
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "health_check/logicmodule_health_check.sh"]
       
  ####################################
  #  JAVA DATA SERVICES ON DC 1      #
  ####################################

  ds1java1:
    image: "bscdataclay/dsjava:${DATACLAY_CONTAINER_VERSION}"
    depends_on:
      - logicmodule1
    ports:
      - 2127
    env_file:
      - ./env/DS.environment
      - ./env/LM.environment
    environment:
      - DATASERVICE_NAME=DS1
    volumes:
      - ./prop/global.properties:/usr/src/dataclay/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/usr/src/dataclay/log4j2.xml:ro
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "health_check/dataservice_health_check.sh"]
